name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:            
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup PostgreSQL for Linux/macOS/Windows
      uses: ikalnytskyi/action-setup-postgres@v5

    - name: Build
      uses: actions/checkout@v3

    - name: Install apt https
      run: sudo apt-get update && sudo apt-get install -y apt-transport-https
      
    - name: Setup OpenCV
      run: sudo apt-get install -y opencv-data
          
      
    - name: Run tests
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost/postgres
      run: cargo test --verbose

